### ISSUE TITLE
add aws-sdk v3 support

### ISSUE THREAD

**Issue by jgilbert01** [jgilbert01/aws-lambda-stream#308]

**Comment by cmeadowscb** [comment]
Is there an estimated timeline on when this is expected to be available in a release?  With the Node 16 support dropping in AWS in June it seems like this might become urgent.

**Comment by jgilbert01** [comment]
> Is there an estimated timeline on when this is expected to be available in a release? With the Node 16 support dropping in AWS in June it seems like this might become urgent.

- we have all the connectors updated to v3 and we are doing regression testing
- it will be part of the 1.0.0 release
- so it should be ready soon

**Comment by cmeadowscb** [comment]
Awesome!  Thank you for your quick response.

**Comment by jgilbert01** [comment]
- i just published 1.0.0 w sdk v3
- https://github.com/jgilbert01/aws-lambda-stream/pull/337
- give it a test drive
