### ISSUE TITLE
deprecation notice - uuid

### ISSUE THREAD

**Issue by kmudrick** [jgilbert01/aws-lambda-stream#309]
When installing, I got a deprecation notice about `uuid`:

> Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

Looks like there are performance optimizations in more recent versions than the `3.x` line as well.

**Comment by petermyers** [comment]
I believe this is resolved with the latest version which upgrades uuid to 9.x
