### ISSUE TITLE
Exception thrown by fromDynamodb for my table format

### ISSUE THREAD

**Issue by Ankcorn** [jgilbert01/aws-lambda-stream#39]
First i'd just like to say this library looks amazing! Very cool. I have so many use cases it could serve.

I gave it a test for a dynamodb stream but got an exception from `fromDynamodb(event)`

The tables primary partition key is called id, and it does not have a sk or descriminator.

Unfortunatly migrating the data is not an option right now.

These 2 lines throw exceptions.

https://github.com/jgilbert01/aws-lambda-stream/blob/db17e6da8838477a77451369321d086ee82b0f59/src/from/dynamodb.js#L49

 https://github.com/jgilbert01/aws-lambda-stream/blob/db17e6da8838477a77451369321d086ee82b0f59/src/from/dynamodb.js#L26

I'd happily make a PR but am not exactly sure what a reasonable approach is.

**Comment by jgilbert01** [comment]
sounds good, i'll take a look at making this configurable.

**Comment by Ankcorn** [comment]
Thanks, If there is anything I can do to help let me know.

I tried to clone the library and get the tests working but I think I might be missing something. The pretest script started shouting at me with something to do with the aws sdk.

**Comment by jgilbert01** [comment]
please review this PR to see if it meets your needs: https://github.com/jgilbert01/aws-lambda-stream/pull/40

thx

**Comment by Ankcorn** [comment]
Thanks!

**Comment by jgilbert01** [comment]
0.3.0 published
