### ISSUE TITLE
[evaluate flavor] Consistent reads are not supported on global secondary indexes

### ISSUE THREAD

**Issue by snegostup** [jgilbert01/aws-lambda-stream#60]
Hi,
[Here](https://github.com/jgilbert01/aws-lambda-stream/blob/a04dbe9b86e48cdc0512d905f9f9e7240a1904ed/src/flavors/evaluate.js#L139), query request to DataIndex  contains `ConsistentRead: true` which throws `ValidationException: Consistent reads are not supported on global secondary indexes`. Looks like consistent reads are not supported on global secondary indexes, as per [documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadConsistency.html).

**Comment by jgilbert01** [comment]
Thx! It is fixed in 0.6.0
