### ISSUE TITLE
Some 'src/from' modules don't get exported into library namespace

### ISSUE THREAD

**Issue by snegostup** [jgilbert01/aws-lambda-stream#69]
[src/from/index.js](https://github.com/jgilbert01/aws-lambda-stream/blob/b334b778e06e688e6df6ca166c601520945692ad/src/from/index.js):
```javascript
export * from './dynamodb';
export * from './eventbridge';
export * from './kinesis';
```
The `s3.js`, `sns.js` and `sqs.js` are missing!

**Comment by jgilbert01** [comment]
fixed in 0.7.0
Thx!!
